- name: Update system
  ansible.builtin.dnf:
    update_only: true
  
- name: Upgrade all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Install yum-utils
  ansible.builtin.dnf:
    name: yum-utils
    state: present

- name: Add Docker CE repository
  ansible.builtin.command: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Install docker-ce
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin

- name: Start and enable the docker deamon
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes

- name: Verify Docker installation
  command: docker --version
  register: docker_version

- debug:
    msg: "Docker installed: {{ docker_version.stdout }}"