---
- name: Install nginx
  ansible.builtin.dnf:
    name: 
      - epel-release
      - nginx
    update_cache: true

- name: Ensure sites-enabled directory exists
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled
    state: directory

- name: Ensure default web root exists
  ansible.builtin.file:
    path: /var/www/html
    state: directory