- name: Set ACLs
  belair10.ad.acl:
    object: "{{item.value.object}}"
    principal: "{{item.value.principal}}"
    rights: "{{item.value.rights}}"
    object_type: "{{item.value.object_type|default('')}}"
    inherit: "{{item.value.inherit|default('None')}}"
    inherited_object_type: "{{item.value.inherited_object_type|default('')}}"
    type: allow
  loop: "{{ad_acls | dict2items}}"
#   register: acl

# - debug:
#     msg: "{{acl}}"
