- name: "Prepare to trust flush and renew dns"
  win_shell: |
    ipconfig /flushdns
    ipconfig /renew

- name: Create bidirectional trusts
  ansible.windows.win_powershell:
    script: |
      [CmdletBinding()]
      param(
          [String]
          $localDomain,
          $remoteDomain,
          [PSCredential]
          $localCred,
          $remoteCred
      )

      if (-not (Get-ADTrust -Filter "Target -eq '$remoteDomain'")) {
        $res = netdom trust $($localdomain) /domain:$($remoteDomain) /add /userd:$($remoteCred.Username) /twoway /passwordd:$($remoteCred.GetNetworkCredential().Password) /usero:$($localCred.Username) /passwordo:$($localCred.GetNetworkCredential().Password)
        if (-not $res) {
          $Ansible.Failed = $true
          $Ansible.Result = "Check if trust file exists already"
        }
      }
      else {
        $Ansible.Changed = $false
      }
    parameters:
      localDomain: "{{domain}}"
      remoteDomain: "{{item.key}}"
    sensitive_parameters:
    - name: localCred
      username: "{{domain_admin_username}}"
      password: "{{domain_admin_password}}"
    - name: remoteCred
      username: "administrator@{{item.key}}"
      password: "{{lab.domains[item.key].domain_password}}"
  loop: "{{trusts | dict2items}}"
  when: item.value.type == 'Bidirectional'

- name: Create inbound trusts
  ansible.windows.win_powershell:
    script: |
      [CmdletBinding()]
      param(
          [String]
          $localDomain,
          $remoteDomain,
          $trustPassword,
          [PSCredential]
          $localCred,
          $remoteCred
      )

      if (-not (Get-ADTrust -Filter "Target -eq '$remoteDomain'")) {
        netdom trust $($remoteDomain) /domain:$($localdomain) /add /oneside:trusted /usero:$($localCred.Username) /passwordo:$($localCred.GetNetworkCredential().Password) /passwordt:$($trustPassword)
        if (-not $?) {
          $Ansible.Failed = $true
          $Ansible.Result = "Check if trust file exists already"
        }
      }
      else {
        $Ansible.Changed = $false
      }
    parameters:
      localDomain: "{{domain}}"
      remoteDomain: "{{item.key}}"
      trustPassword: "{{trust_password}}"
    sensitive_parameters:
    - name: localCred
      username: "{{domain_admin_username}}"
      password: "{{domain_admin_password}}"
    - name: remoteCred
      username: "administrator@{{item.key}}"
      password: "{{lab.domains[item.key].domain_password}}"
  loop: "{{trusts | dict2items}}"
  when: item.value.type == 'Inbound'

- name: Create outbound trusts
  ansible.windows.win_powershell:
    script: |
      [CmdletBinding()]
      param(
          [String]
          $localDomain,
          $remoteDomain,
          $trustPassword,
          [PSCredential]
          $localCred,
          $remoteCred
      )

      if (-not (Get-ADTrust -Filter "Target -eq '$remoteDomain'")) {
        netdom trust $($localdomain) /domain:$($remoteDomain) /add /oneside:trusting /usero:$($localCred.Username) /passwordo:$($localCred.GetNetworkCredential().Password) /passwordt:$($trustPassword)
        if (-not $?) {
          $Ansible.Failed = $true
          $Ansible.Result = "Check if trust file exists already"
        }
      }
      else {
        $Ansible.Changed = $false
      }
    parameters:
      localDomain: "{{domain}}"
      remoteDomain: "{{item.key}}"
      trustPassword: "{{trust_password}}"
    sensitive_parameters:
    - name: localCred
      username: "{{domain_admin_username}}"
      password: "{{domain_admin_password}}"
    - name: remoteCred
      username: "administrator@{{item.key}}"
      password: "{{lab.domains[item.key].domain_password}}"
  loop: "{{trusts | dict2items}}"
  when: item.value.type == 'Outbound'
  

# - name: Create one-way trusts
#   ansible.windows.win_powershell:
#     script: |
#       netdom trust fv.mil.se /domain:lfv.se /add /userd:LFV\Administrator /passwordd:Toortoor1337 /usero:MIL\Administrator /passwordo:Toortoor1337

# - name: Verify that trust works with Kerberos
#   ansible.windows.win_powershell:
#     script: |
#       netdom trust MyDomain /domain:devgroup.example.com /verify /kerberos /userd:devgroup\admin /passwordd:* /usero:MyDomain\admin /passwordo:*

# check https://github.com/lewill03/ADTrust/blob/main/ADTrust.psm1