- name: Create universal groups
  microsoft.ad.group:
    name: "{{ item.key }}"
    scope: universal
    path: "{{ item.value.path }}"
    state: present
  with_dict: "{{ ad_groups['universal'] }}"
  when: ad_groups['universal'] is defined and item.value.managed_by is not defined

- name: Create global groups
  microsoft.ad.group:
    name: "{{ item.key }}"
    scope: global
    path: "{{ item.value.path }}"
    state: present
  with_dict: "{{ ad_groups['global'] }}"
  when: ad_groups['global'] is defined and item.value.managed_by is not defined

- name: Create domain local groups
  microsoft.ad.group:
    name: "{{ item.key }}"
    scope: domainlocal
    path: "{{ item.value.path }}"
    state: present
  with_dict: "{{ ad_groups['domainlocal'] }}"
  when: ad_groups['domainlocal'] is defined and item.value.managed_by is not defined