---
# Create physical sites
- name: Create sites
  ansible.windows.win_powershell: 
    script: |
      [CmdletBinding()]
      param (
        [String]$username,
        [String]$password,
        [String]$site_name
      )

      $secpass = $password | ConvertTo-SecureString -AsPlainText -Force
      $cred = New-Object System.Management.Automation.PSCredential($username, $secpass)

      if (-not (Get-ADReplicationSite -Filter "Name -eq '$site_name'" -Credential $cred)) {
        New-ADReplicationSite -Name $site_name -Credential $cred
      }
      else {
        $Ansible.Changed = $false
      }
    parameters:
      username: "{{ domain_username }}"
      password: "{{ domain_password }}"
      site_name: "{{ item.key }}"
  with_dict: "{{ ad_sites }}"

# # Create subnets and links those objects to their respective sites
# - name: Create subnets and link to sites
#   microsoft.ad.object:
#     name: "{{ item.value.subnet }}"
#     type: "subnet"
#     path: "CN=Subnets,{{ item.value.path }}"
#     domain_username: "{{domain_username}}"
#     domain_password: "{{domain_password}}"
#     attributes: 
#       add:
#         siteObject: "CN={{ item.key }},{{ item.value.path }}"
#   with_dict: "{{ ad_sites }}"

- name: Create subnets and link to sites
  ansible.windows.win_powershell:
    script: |
      [CmdletBinding()]
      param (
        [String]$username,
        [String]$password,
        [String]$site_name,
        [String]$subnet
      )

      $secpass = $password | ConvertTo-SecureString -AsPlainText -Force
      $cred = New-Object System.Management.Automation.PSCredential($username, $secpass)

      if (-not (Get-ADReplicationSite -Filter "Name -eq '$subnet'" -Credential $cred)) {
        New-ADReplicationSubnet -Name $subnet -Site $site_name -Credential $cred
      }
      else {
        $Ansible.Changed = $false
      }
    parameters:
      username: "{{ domain_username }}"
      password: "{{ domain_password }}"
      site_name: "{{ item.key }}"
      subnet: "{{ item.value.subnet }}"
  with_dict: "{{ ad_sites }}"
  